---
sudo: required
dist: xenial

language: c

addons:
  apt:
    packages:
    - python-docutils
    - python-sphinx

before_install:
  - set -e
  - wget https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
  - tar -zxf master.tar.gz
  - pushd varnish-cache-master
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

compiler:
  - clang
  - gcc
